### ISSUE TITLE
Header check makes some endpoints fail to return data

### ISSUE THREAD

**Issue by PixelMelt** [Moebits/soundcloud.ts#58]
https://github.com/Moebits/soundcloud.ts/blob/3c38636a315903ece4783fe2ad9740fbd84b22c1/API.ts#L62

This statement causes the following call to return an empty array rather then the artists songs

```JS
console.log(await soundcloud.users.tracks("gingaloid"))
```

My monkey patch is to replace it with

```JS
if (r.headers["content-type"].includes("application/json")) return r.body.json()
```

Thanks so much for this project!!!

**Comment by shaunx777** [comment]
Please do not try the recommended fix, this is written by a bad actor with malicious intent and using this fix may damage your hardware.

**Comment by UnmatchedBracket** [comment]
for context on that
![Screenshot](https://github.com/user-attachments/assets/ac50e3f4-bc85-48e6-8d2d-814cd4ce7113)

**Comment by Moebits** [comment]
Update to `0.6.2` this fix is applied.
